server:
  port: 80
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/questionlibiary?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 111111



